CREATE TABLE IF NOT EXISTS `pres_hist` (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   status BOOLEAN NOT NULL,
   lastseen BIGINT,
   sub_id INTEGER REFERENCES subs(id),
   tag VARCHAR(8),
   ts DATETIME DEFAULT CURRENT_TIMESTAMP
);
